In [10]:
import os
import nltk

# nltk.download()


# Embedding Algos

1. OneHotEncodding
2. LabelEncodding
3. Bag of Words
4. TF-IDF
5. Word2Vec

In [11]:
text='''
The Battle of Longewala: A Stand in the Desert

The Thar Desert stretched endlessly under the cold December sky, its sands whispering secrets of time. On the night of December 4, 1971, at the remote Indian border post of Longewala in Rajasthan, Major Kuldip Singh Chandpuri stood watch. His company, 120 soldiers of the 23rd Battalion, Punjab Regiment, manned a small outpost surrounded by a single strand of wire—originally strung by the Border Security Force (BSF) to keep camels from wandering. This wire, frail as it seemed, would soon play a role in one of the most extraordinary battles of the Indo-Pakistani War of 1971.

The war had erupted the previous day, December 3, sparked by Pakistan’s preemptive air strikes on Indian airfields. The conflict’s heart lay in East Pakistan, where Bengali nationalists fought for independence, forming Bangladesh. India, burdened by millions of refugees fleeing Pakistani atrocities, launched a campaign to liberate the east. The western front, including Longewala, was meant to be a holding operation—a defensive line to prevent Pakistan from seizing Indian territory to use as a bargaining chip. But Pakistan had other plans.

Major Chandpuri, a 31-year-old officer with a steely resolve, knew Longewala’s strategic value. The post sat along a lone road to Jaisalmer, a path to deeper Indian territory. Pakistan’s 51st Infantry Brigade, backed by the 22nd Armoured Regiment—some 2,000 to 7,000 troops and 30 to 100 tanks—aimed to overrun Longewala, capture Ramgarh, and threaten Jaisalmer’s airfield. Their commanders, confident in their numbers, assumed the post was lightly defended, unaware that the BSF had handed it to Chandpuri’s company.

As dusk fell, Second Lieutenant Dharam Vir Bhakhri, a 26-year-old officer, led a patrol near the border pillar, 15 kilometers from the post. The desert was silent until a distant hum broke the stillness. Peering through his binoculars, Dharam Vir’s heart raced. A massive column of Pakistani tanks—Chinese Type 59s and Shermans—rumbled forward, followed by thousands of infantry. He radioed Chandpuri: “Enemy advancing. Tanks and troops, thousands strong.”

Chandpuri’s mind raced. His company had two medium machine guns, two 81mm mortars, four rocket launchers, and small arms—no match for armored columns. No minefields or barbed wire fortified the post, only that deceptive strand of wire. Retreat was an option, but fleeing on foot through the desert meant abandoning the post and risking encirclement. Chandpuri gathered his men. “We hold until reinforced,” he declared, his voice steady. “This is our post, our duty.”

The soldiers, mostly Sikhs from Punjab, nodded. Chandpuri, drawing on their shared heritage, spoke of Guru Gobind Singh’s courage against overwhelming odds. “I won’t leave,” he said. “Anyone who wishes may go.” None moved. They trusted their major, a man who led from the front, moving bunker to bunker to bolster morale.

At midnight, the Pakistani assault began. Tanks roared, their tracks churning the sand, but the single wire fooled the infantry into believing a minefield lay ahead. Hesitation crept in. Pakistani commanders, lacking air cover and engineer reconnaissance, had miscalculated. Their tanks, reliant on external fuel tanks, were vulnerable, and the unfamiliar terrain bogged them down. Chandpuri’s men opened fire, their machine guns and mortars spitting defiance. The wire, mistaken for a minefield, stalled the infantry, who lost the cover of darkness.

Dharam Vir, back at the post, coordinated fire. “Reference Longewala well, gole barsa!” Chandpuri shouted in Punjabi, directing artillery from Sadhewala. Captain Santosh Datta, an artillery officer, arrived at dawn, refining the barrage. The Indian fire was precise, but the tanks kept coming. Chandpuri, wounded twice, refused to retreat, rallying his men with a bayonet charge that sowed panic among the Pakistanis.

As dawn broke on December 5, the desert sky roared with salvation. Six Hawker Hunter jets from Jaisalmer’s 122 Squadron, led by Wing Commander M.S. Bawa, screamed overhead. The Pakistanis, exposed without air cover, were sitting ducks. The Hunters, armed with T-10 rockets and 30mm Aden guns, unleashed hell. Tanks erupted in flames, their external fuel tanks igniting. By noon, 22 tanks lay destroyed by air strikes, 12 by ground fire, and two were captured—abandoned by fleeing crews. Over 100 vehicles littered the desert, and 200 Pakistani soldiers were dead.

The Pakistani offensive crumbled. Indian reinforcements—tanks from the 20th Lancers and the 17th Rajputana Rifles—arrived, led by Colonel Bawa Guruvachan Singh. A counteroffensive mopped up stragglers, ending the six-hour battle. Longewala stood unbroken.

The victory was staggering. Chandpuri’s 120 men, with IAF support, had repelled a force 20 times their size. Pakistan’s plan to seize Indian territory collapsed, leaving them no leverage in negotiations. The eastern campaign continued, culminating in Dhaka’s fall on December 16, birthing Bangladesh.

Chandpuri earned the Maha Vir Chakra, India’s second-highest gallantry award. His citation praised his “dynamic leadership” and “exceptional courage.” Dharam Vir received a Mention in Dispatches, though his family later felt he deserved more. The IAF’s role, emphasized in books like *The Epic Battle of Longewala* by Air Marshal Bharat Kumar, was pivotal, with Hunters destroying over 40 tanks. Yet, some, like Major General Atma Singh, argued the IAF’s air observation posts deserved greater credit for guiding strikes.

The battle inspired J.P. Dutta’s 1997 film *Border*, with Sunny Deol as Chandpuri and Akshaye Khanna as a fictionalized Dharam Vir, who was depicted as martyred. In reality, Dharam Vir survived, retiring as a colonel. The film, while romanticized, immortalized Longewala, though it sparked debate over whether the army or IAF deserved more credit. Chandpuri, ever humble, sued for one rupee in 2008 to defend his company’s honor against claims they vacated the post.

Longewala became India’s “Battle of Thermopylae,” a stand against overwhelming odds, celebrated by British media and visited by Field Marshal R.M. Carver. The Longewala War Memorial, with its museum and captured tanks, stands as a testament to the 120 soldiers and IAF pilots who turned the desert into a graveyard for Pakistan’s ambitions.

For Chandpuri, the battle was duty fulfilled. “I was given a task in writing,” he told Carver. “I executed it.” The small temple at the post, maintained by his men despite shelling, symbolized their unity. “It has miraculous powers,” Chandpuri later said, visiting it years after retiring as a brigadier.

The sands of Longewala still whisper of that night—when courage, strategy, and airpower wrote a legend in the desert.

[Word count: ~2500, approximately 10 pages double-spaced]
'''

In [12]:
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer



ps=PorterStemmer()
lemmatizer=WordNetLemmatizer()
sentence=nltk.sent_tokenize(text)
# stop_words=stopwords.words('english')

coupus=[]


for i in range(len(sentence)):
    review=re.sub('[^a-zA-Z]',' ',sentence[i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review=[lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review=' '.join(review)
    coupus.append(review)



In [13]:
coupus

['battl longewala stand desert thar desert stretch endlessli cold decemb sky sand whisper secret time',
 'night decemb remot indian border post longewala rajasthan major kuldip singh chandpuri stood watch',
 'compani soldier rd battalion punjab regiment man small outpost surround singl strand wire origin strung border secur forc bsf keep camel wander',
 'wire frail seem would soon play role one extraordinari battl indo pakistani war',
 'war erupt previou day decemb spark pakistan preemptiv air strike indian airfield',
 'conflict heart lay east pakistan bengali nationalist fought independ form bangladesh',
 'india burden million refuge flee pakistani atroc launch campaign liber east',
 'western front includ longewala meant hold oper defens line prevent pakistan seiz indian territori use bargain chip',
 'pakistan plan',
 'major chandpuri year old offic steeli resolv knew longewala strateg valu',
 'post sat along lone road jaisalm path deeper indian territori',
 'pakistan st infantri brig

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x_how=cv.fit_transform(coupus)
print(x_how.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


## TF_IDF


- TF (Term Frequnecy) = No. of repeation of word in sentenc / No. of words in  sentences
- IDF (Inverse Documnet Frequnecy)= log(No. of sentences / No. of sentences with word)
- TF_IDF = TF * IDF

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf=TfidfVectorizer()

x_how=tf_idf.fit_transform(coupus)
print(x_how.toarray())

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.31376825 0.        ]
 [0.         0.         0.         ... 0.33735011 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


# Word To Vector

- Word2Vec is a two-layer neural network that processes text.
- It takes as its input a large corpus of text and produces a vector space, typically of several hundred dimensions, with each unique word in the corpus being assigned a corresponding vector in the space.
- Word vectors are positioned in the vector space such that words that share common contexts in the corpus are located in close proximity to one another in the space.


In [5]:
# ! pip install transformers

In [6]:
from transformers import AutoTokenizer, AutoModelForCausalLM

# Load a pre-trained model and tokenizer
model_name = "gpt2"  # You can replace with any other LLM
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

def chunk_text(text, max_length=512):
    """Chunk text into smaller pieces."""
    tokens = tokenizer.encode(text, return_tensors='pt')[0]
    chunks = []
   
    for i in range(0, len(tokens), max_length):
        chunk = tokens[i:i + max_length]
        chunks.append(chunk)

    return chunks

def generate_responses(chunks):
    """Generate responses for each chunk using the LLM."""
    responses = []
    for chunk in chunks:
        input_ids = chunk.unsqueeze(0)  # Add batch dimension
        output = model.generate(input_ids, max_length=100)  # Generate response
        responses.append(tokenizer.decode(output[0], skip_special_tokens=True))
   
    return responses

# Example long text
long_text = "Your long text goes here. " * 50  # Repeat to simulate long text

# Chunk the text
chunks = chunk_text(long_text)

# Generate responses for each chunk
responses = generate_responses(chunks)

# Print the responses
for i, response in enumerate(responses):
    print(f"Response for chunk {i+1}:\n{response}\n")

ImportError: 
AutoModelForCausalLM requires the PyTorch library but it was not found in your environment. Checkout the instructions on the
installation page: https://pytorch.org/get-started/locally/ and follow the ones that match your environment.
Please note that you may need to restart your runtime after installation.
